name: build

on:

  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        device: [g84]
    name: "ðŸš§ Build for ${{matrix.device}}"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"

      - name: Setup Toolchains
        run: |
          sudo apt update
          sudo apt install bison flex libssl-dev libarchive-tools -y
          mkdir -p toolchain
          cd toolchain
          echo 'Download antman and sync'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S=05012024
          echo 'Patch for glibc'
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") --patch=glibc
          echo 'Done'

      - name: Run build
        run: |
          DEVICE=${{matrix.device}} ./build.sh -d

      - name: Upload kernel
        uses: actions/upload-artifact@v4
        with:
          name: outdir
          path: out/
